version: '3'

services:
  express:
    build: ./
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_tables
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_tables
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
  # proxy:
  #   image: nginx
  #   volumes:
  #       - ~/nginx/conf:/etc/nginx/conf.d
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - express
networks:
  default:
    name: nginx-net
    external: true
volumes:
  db-data: