version: '3'

services:
  express:
    build: ./
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_tables
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  db-data: