version: '3'

services:
  express:
    build: ./
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_tables
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_tables
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data: